### ISSUE TITLE
Confusing benchmark result

### ISSUE THREAD

**Issue by Kjaer** [vitaly-t/chain-arrays#1]
Hey there @vitaly-t,

I am testing out your chain array utility, and get results of chain array got slower compare to good ol' array's `concat` method. 
What the heck am I doing wrong?

Here is my test arrays (attached)
[test_arrays.zip](https://github.com/user-attachments/files/17947306/test_arrays.zip)

and this is my benchmark code:

```javascript
import { chainArrays } from "./chain-array.mjs";
import timestampArray1 from "./timestampArray1.mjs"
import timestampArray2 from "./timestampArray2.mjs";

function benchmark() {
  var chainArrStart = Date.now();
  var mergedArr = [];

  var mergedArrTemp = chainArrays(timestampArray1, timestampArray2);
  for (const logItem of mergedArrTemp) {
    mergedArr.push(logItem);
  }

  console.log(`Iteration: ${Date.now() - chainArrStart}ms; mergedArr: ${mergedArr.length}`);

  var concatStart = Date.now();
  var mergedArr2Temp = timestampArray1.concat(timestampArray2);
  var mergedArr2 = [];

  for (const logItem2 of mergedArr2Temp) {
    mergedArr2.push(logItem2);
  }
  console.log(`Iteration: ${Date.now() - concatStart}ms; mergedArr2: ${mergedArr2.length}`);

}

benchmark();
```

Result:
![image](https://github.com/user-attachments/assets/9ed51cf4-d526-4024-8abf-3d163424f0d2)

I am using node.js `22.11.0`

**Comment by vitaly-t** [comment]
You do not have enough input data to get speed benefits of `chain-arrays`. You can see that in the test shown on the main page, we used 5 arrays, each with 10mln records. And you've got 2 arrays with just 100,000 records in each. For such small data, the native `concat` will always perform better, even though it will use more memory.

Also, your very test logic is wrong. You cannot push values into memory for array-join test, designed to save on memory usage, you are effectively cancelling the befit of memory reuse right there, by forcing it to occupy twice the amount of memory anyway.

**Comment by Kjaer** [comment]
I get it what you mean, So I increase the volume of testing arrays, (~9M of item in total split into 7 array and 2 copy of it) and instead of pushing the result into new array, I just iterate over the finals.

new benchmark:
```javascript
import { chainArrays } from "./chain-array.mjs";
import timestampArray1 from "./timestampArray1.mjs";
import timestampArray2 from "./timestampArray2.mjs";
import timestampArray3 from "./timestampArray3.mjs";
import timestampArray4 from "./timestampArray4.mjs";
import timestampArray5 from "./timestampArray5.mjs";
import timestampArray6 from "./timestampArray6.mjs";
import timestampArray7 from "./timestampArray7.mjs";

function benchmark() {
  var chainArrStart = Date.now();
  var timestampArrGeneric = Array.from(timestampArray3);
  var timestampArrGeneric2 = Array.from(timestampArray2);

  var mergedArr = chainArrays(
    timestampArray1,
    timestampArray2,
    timestampArray3,
    timestampArray4,
    timestampArrGeneric,
    timestampArrGeneric2,
    timestampArray5,
    timestampArray6,
    timestampArray7
  );

  var tsIterator = mergedArr[Symbol.iterator]();

  do {
    var logItem = tsIterator.next();
  } while (!logItem.done);

  console.log(
    `Iteration: ${
      Date.now() - chainArrStart
    }ms; mergedArr: ${mergedArr.getLength()}`
  );

  var concatStart = Date.now();
  var mergedArr2 = timestampArray1
    .concat(timestampArray2)
    .concat(timestampArray3)
    .concat(timestampArray4)
    .concat(timestampArrGeneric)
    .concat(timestampArrGeneric2)
    .concat(timestampArray5)
    .concat(timestampArray6)
    .concat(timestampArray7);

  mergedArr2.forEach((item) => item);

  console.log(
    `Iteration: ${Date.now() - concatStart}ms; mergedArr2: ${mergedArr2.length}`
  );
}

benchmark();
```

and now I am able to get the optimised result:
![image](https://github.com/user-attachments/assets/14c4e5db-c06f-4d98-ac5f-cbc3ac216045)

**Comment by vitaly-t** [comment]
The important thing is to see what happens to the memory during the same tests. Using `arrays-chain`, the memory use remains unchanged, while `concat` will consume a lot more memory. This ultimately makes `arrays-chain` approach more scalable when dealing with large data.

**Comment by Kjaer** [comment]
true, because `chainArrays` don't create new arrays, it just iterate over given arrays. So arrays stay intact and `Iterator` you created artificially just become a glue between them. It allows me to iterate over without worrying which array I should iterate over next. Actually this technique started to grow on me.

**Comment by vitaly-t** [comment]
Better yet, any of the source arrays may suddenly change its content, and the returned `Iterable` will still work correctly, as the iteration is fully dynamic. In other words, you can mutate data in arrays and the processor doesn't need to know about it, as it will continue working automatically.
